### ISSUE TITLE
style.css is not fully compiled in lib folder

### ISSUE THREAD

**Issue by ingro** [buildo/rc-datepicker#102]
Hello! I just updated to 5.0 and have an issue with styles.
The bundled `lib/style.css` is not fully compiled, referring to relative imports like `@import url(~react-flexview/lib/flexView.css);` and `@import url(./icons.css);`, and thus giving me errors when I import it with webpack.

**Comment by FrancescoCioria** [comment]
thank you for reporting this @ingro
We'll fix it asap

**Comment by ingro** [comment]
Thanks for the fast fix @FrancescoCioria !
