### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by kerosan** [buildo/rc-datepicker#105]
plaese create *.d.ts file

**Comment by FrancescoCioria** [comment]
Hi @alukard1986 , we'll try to add it in the following weeks :)

**Comment by giogonzo** [comment]
Hi @kerosan , a .d.ts file has been added in #119 and released with [v5.0.6](https://github.com/buildo/rc-datepicker/blob/master/CHANGELOG.md#v506-2017-05-05)
Please give it a try and report back if you encounter any issue!
