### ISSUE TITLE
Can not find lib/style.css.

### ISSUE THREAD

**Issue by novemberde** [buildo/rc-datepicker#111]
I used DatePickerInput component since 2 month ago.

but my colleague did "npm update" today and then React project can not find <lib/style.css> now.

It make that DatePickerInput component doesn't look like before. After that, All of datepicker component style is native.

Also I already added <styles.js> in root folder but it's not work well.

How to apply default style of component now?

**Comment by giogonzo** [comment]
Hi @novemberde, thanks for pointing this out!

Looks like `v5.0.2` somehow introduced this regression.
I just published `v5.0.3` which should fix it (`lib/style.css` should be there)

Let me know if it works for you
