### ISSUE TITLE
use a debug log library

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/rc-datepicker#12]
keep forgetting some console.log around...

**Comment by giogonzo** [comment]
I'd just use https://github.com/visionmedia/debug everywhere

**Comment by FrancescoCioria** [comment]
I saw that Facebook for React warnings is using normal ```console.warn``` but only if ```process.env.NODE_ENV !== 'production'```
This is useful to log warning for developers without them having to enable our ```debug``` logs.
Should use both ```debug``` for our development logs and ```console.warn``` for warnings? (if ```process.env.NODE_ENV !== 'production'```)

/cc @gabro

**Comment by gabro** [comment]
That makes sense to me, @giogonzo?

**Comment by giogonzo** [comment]
definitely, dev debug and user warnings are totally different beasts

`console.warn` should be safe everywhere now: http://caniuse.com/#feat=console-basic
