### ISSUE TITLE
add support for valueLink

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/rc-datepicker#13]

**Comment by FrancescoCioria** [comment]
@gabro 
usually React components work with ```value``` and ```onChange``` but our datepicker accepts ```date``` instead of ```value```.
Do you think we should standardize it?
PS: ```valueLink``` support can be added also if we keep ```date```

**Comment by gabro** [comment]
Let's use `value`, it makes more sense in the context of standard components API

**Comment by FrancescoCioria** [comment]
agreed

**Comment by FrancescoCioria** [comment]
for the change of the API please refer to this issue: #39
