### ISSUE TITLE
Disable user input?

### ISSUE THREAD

**Issue by kennethkoontz** [buildo/rc-datepicker#149]
I have a use case where I'd like the user to only be able to modify the date by clicking on the datepicker. Right now, the user could manually modify the date in the input which gives me the impression that the date could be put into an invalidate state by the user. If the user could only select the date, the user couldn't put the date into an invalid state. Is there are setting or an approach on how one might accomplish this?

**Comment by Santhosh1392** [comment]
@kennethkoontz Try passing readOnly prop to the DatePickerInput component, It will make the input field to read only.

**Comment by cornelism** [comment]
this is correct and can be closed.

Thank you, Santhosh1392
