### ISSUE TITLE
should we introduce t-comb for prop and type checking?

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/rc-datepicker#38]
I think t-comb might be useful in a complex set of components as this one.
/cc @gabro @gcanti

**Comment by gcanti** [comment]
I think tcomb would be an additional dependency (3K gizipped) with no real value for your users

**Comment by gabro** [comment]
@FrancescoCioria what would you use tcomb for? Maybe you can roll your own utility functions instead of brining in a new dependency

**Comment by FrancescoCioria** [comment]
Actually I'm already using some utility functions, this issue was more a question then a technical issue, I wanted to understand if it made any sense introducing ```t-comb```

**Comment by FrancescoCioria** [comment]
I'm closing this issue
