### ISSUE TITLE
Use Radium

### ISSUE THREAD

**Issue by gcedo** [buildo/rc-datepicker#51]
As of today, the component is shipped with an optional css stylesheet. I also saw that in `DatePicker` and `DatePickerInput`, there is the `style` prop, meant to override the style.

How about switching to [Radium](https://github.com/FormidableLabs/radium)? In this way you could pack your component with a default style that does not depend on an external file. If the user wants to override that style, he can pass a style object to the root component that will be merged with the base style, overriding the values of the matching keys.

If you agree I can work on a PR to achieve this.

**Comment by giogonzo** [comment]
This is a long standing issue for many of our components, and react components in general. Every approach has some non trivial drawback, e.g. using Radium, you're not able to pack css in an external css bundle (this was true last time I checked, maybe it is not the case anymore). Here's a comparison table with Radium and more tools https://github.com/FormidableLabs/radium/tree/master/docs/comparison

We also tried [react-style](https://github.com/js-next/react-style), which has a build step (good), but on the other hand lacks in helpers for pseudo classes, on hover and such

For our apps we're currently using an approach similar to [BEM](https://medium.com/seek-ui-engineering/block-element-modifying-your-javascript-components-d7f99fcab52b)
[Here's an interesting](https://github.com/cyclejs/cycle-core/issues/128) (and way too long) discussion related to components and styling in general

Current situation (base stylesheet as css + overridable inline style) seems like a good balance (although it's admittedly not handy having to import the separate stylesheet in your app build). If we were to remove the external stylesheet, we could just go with `style=` (avoiding the biggish Radium dependency)

So I'm not that sold on Radium in particular, but I could be missing something in the big picture. @gcedo could you provide examples of how component API would be affected by the proposed changes and how it would be better for users (considering that bundling css could be important for *some* user)?

/cc @FrancescoCioria

**Comment by gcedo** [comment]
I had started to sketch something that looks like this

```javascript
// styles.js
export const DatePicker = {
    base: { backgroundColor: 'red' },
    ':hover': { /* ... */ }
}

export const DatePickerInput = { /**/ }
export const Picker = {
    top: {}, 
    body: {}, 
    base: {} 
}
```

Then, say from the `DatePicker` component:

```javascript
import {DatePicker} as style from 'style.js';
// [...]
<div style={[style.base, this.props.style]} />
```

I think the benefits of this approach are:
* Rules overriding is easy and can be applied to every part of the component
* The style is packed in your component, no need for an external css file
* Style is applied inline, good performances
* Nesting does not mean a drawback in performances

**Comment by giogonzo** [comment]
> I think the benefits of this approach are:
* Rules overriding is easy and can be applied to every part of the component

provided we have a style config for every element in `DatePicker` template, right?

>* The style is packed in your component, no need for an external css file

As I was saying before, this is of course a benefit in terms of setup when developing, but for a deployed app it is often better to have packed css as proper css, and not recomputing "*static*" inline style at every rerender

>* Style is applied inline, good performances
* Nesting does not mean a drawback in performances

Again, I see many of these benefits but what does Radium add to `DatePicker` compared to plain `style=` justifying the additional radium dependency and kBs?
(just trying to understand here)

**From Radium readme:**
>Conceptually simple extension of normal inline styles

ok

>Browser state styles to support :hover, :focus, and :active
Media queries

nice, altough media queries are not used in this case

>Automatic vendor prefixing

this should be a build time concern in my opinion

>Keyframes animation helper

don't really care

>ES6 class and createClass support

hope so :smiley:

**Comment by giogonzo** [comment]
Also, they don't mention flexbox support anywhere (which is the way the component is currently styled, and how I'd like to layout my components today)

Flexbox from plain js is not feasible, e.g. you cannot provide two different values for the `display` property, like `box` and `flexbox`, which you need to support slightly older browsers

**Comment by gcedo** [comment]
> provided we have a style config for every element in DatePicker template, right?
Yep (a mere transcription of the styles in style.scss)

> Again, I see many of these benefits but what does Radium add to DatePicker compared to plain `style=` justifying the additional radium dependency and kBs?
I would say mostly support for browser state styles. The style merge can be easily achieved with Object.assign or the ES7 `...` operator. 
If that case can be handled with another tool, I am not opinionated about Radium :smiley: 

Maybe the state of this isn't enough mature yet to fully migrate, but I was really fascinated by vjeux talk on styles in js :smiley:

**Comment by giogonzo** [comment]
> I was really fascinated by vjeux talk on styles in js

This pretty much describes my current status as well. I've been trying to go full js on every project and lib I worked on since that, but always resorted to a mixed approach in the end

> I would say mostly support for browser state styles.

exactly
static, flexbox and pseudo styles: css
"state" but non pseudo: js

I think the reason why this approach works flawlessly e.g. for react native is that there you don't have any pseudo styling in the first place, and e.g. `:hover` must be handled as `onHover`/`onHoverOut` anyway

Also, slightly related, if you're not using flexbox everywhere, you should :+1:
Our own [FlexView](https://github.com/buildo/react-components/tree/master/src/flex) or other similar "layout" components also ease the pain of actually using flexbox syntax and support older syntaxes with a [*subjective statement*] good api

**Comment by gcedo** [comment]
> Also, slightly related, if you're not using flexbox everywhere, you should
Some of us have to support IE9 :sob:

**Comment by giogonzo** [comment]
Some of you should convince their boss it is not a good idea :tongue: 

Closing this for now, thanks for the interesting discussion!

Please come back when css in js is ready :smile:

**Comment by gcedo** [comment]
> Some of you should convince their boss it is not a good idea

Or just change their job :heart_eyes_cat:
