### ISSUE TITLE
I am back with CSS :)

### ISSUE THREAD

**Issue by gcedo** [buildo/rc-datepicker#53]
How about this https://github.com/pluralsight/react-styleable?

**Comment by giogonzo** [comment]
Hi there :)

Nice, I like it
Also promising: https://github.com/gajus/react-css-modules (need to look better at it)

I'm totally fine with using this approach for my own app (actually I might give it a spin this week in some of our apps). I already use webpack anyway

>react-styleable assumes that your reusable component and consumers of that component will be using CSS modules.

Unless I'm missing something, this requires webpack fullstack

Problem is, I don't want to force consumers of a library doing it. A library should make by definition no assumptions on the build system. Having an "already built" module also has some practical nice properties, like being able to bring up a jsfiddle with rawgit pointing to lib github repo in *seconds*

**Comment by FrancescoCioria** [comment]
I discussed briefly with @gcedo offline and I'm of the same opinion as @giogonzo.

PS: I hadn't thought of rawgit demos!
