### ISSUE TITLE
January calendar wrong with moment 2.11+

### ISSUE THREAD

**Issue by ingro** [buildo/rc-datepicker#65]
Hello! I'm using your datepicker and found a strange bug. Doesn't matter which locale I choose, january always start on the first day as 1, here's a screenshot:
![datepicker](https://cloud.githubusercontent.com/assets/879431/12322576/3bd8bcfa-bab5-11e5-9e4d-33f8da9b9d82.jpg)

Aftwer some investigation and seeing that the demo online was working I found that the problem was introduced by moment 2.11.0 (2.11.1 also didn't fix the problem). Reverting back to a 2.10.x version of moment solved the problem. The other months seems fine.

**Comment by FrancescoCioria** [comment]
Weird... thanks for the bug report! I'll investigate further

**Comment by ingro** [comment]
@raven-bot I created a pull-request that should fix the problem https://github.com/buildo/rc-datepicker/pull/77

**Comment by FrancescoCioria** [comment]
closed by #77
