### ISSUE TITLE
closeOnClickOutside not triggered when clicking into another DatePickerInput

### ISSUE THREAD

**Issue by djkirby** [buildo/rc-datepicker#69]
Say I have 2 `DatePickerInput`s that are set to `closeOnClickOutside={true}`. If I click the first one, the `DatePicker` pops up, and then if I leave it up and click the second `DatePickerInput`, the first `DatePicker` stays up and the second `DatePicker` is displayed as well. I'm not sure if this is the expected behavior but I would expect the first `DatePicker` to close in this scenario, just like it would if I clicked outside to a normal `<input>`.

**Comment by FrancescoCioria** [comment]
Hi, @djkirby
>  I'm not sure if this is the expected behavior

No, this is definitely a defect, thanks for opening this issue

Right now `DatePickerInput` catches the `click` event and stops its propagation to prevent it to bubble up to the `window` (where it would trigger the close action). We should never stop the click propagation and simply look at the event target on `window` to see if it was generated inside or outside a given `DatePickerInput` node.

**Comment by djkirby** [comment]
:+1: :+1: thanks for the quick reply @FrancescoCioria
