### ISSUE TITLE
3.1.0 break change mode button

### ISSUE THREAD

**Issue by ingro** [buildo/rc-datepicker#75]
After updating to 3.1.0 I noticed the following problem: clicking on the change mode button closes the datepicker!

The problem is not present on the online demo, I suspect they are still running on 3.0.2, but I cloned the repo and then ran the examples locally and I can reproduce the problem.

**Comment by FrancescoCioria** [comment]
Thank you for reporting this bug! As soon as it's fixed I'll release a new version

**Comment by FrancescoCioria** [comment]
@ingro I released `v3.1.1` which should fix this issue

**Comment by ingro** [comment]
Thanks @FrancescoCioria , I can confirm that the problem is fixed!
