### ISSUE TITLE
Find an alternative to valueLink

### ISSUE THREAD

**Issue by ingro** [buildo/rc-datepicker#88]
Since `valueLink` has been deprecated in React 15.0 and it will be removed in 16.0 it would be nice to find an alternative since it's currently used in rc-datepicker.

An easy upgrade path would be, as suggested by React's changelog, to use [this library](https://www.npmjs.com/package/react-linked-input) without changing much in the current code.

**Comment by FrancescoCioria** [comment]
I just looked at the code an we're using `valueLink` on an `input` only in one place (and also erroneously)

I fixed it in #90

**Comment by ingro** [comment]
Great, thanks for your work!
